### ISSUE TITLE
Coverage false positive

### ISSUE THREAD

**Issue by glromeo** [istanbuljs/v8-to-istanbul#170]
I am working on this project https://github.com/glromeo/cypress-c8 to generate code coverage in cypress without using babel.
I have noticed that **a function that's the only export of a module is reported as covered when it shouldn't.**
I did a bit of debugging and the issue seems to be within v8-to-instanbul 

https://github.com/istanbuljs/v8-to-istanbul/blob/53c1cd89cb46f4cd2c0a23cdb31715de09716a2a/lib/v8-to-istanbul.js#L179

maybe for a sourcemap mismatch?

**Comment by glromeo** [comment]
I narrowed it down to this point:
https://github.com/istanbuljs/v8-to-istanbul/blob/53c1cd89cb46f4cd2c0a23cdb31715de09716a2a/lib/source.js#L94-L96

What happens is that in my source file last line was ending at the curly bracket
![image](https://user-images.githubusercontent.com/160981/144757806-7f4b8eb8-0e00-4ac0-b4d8-cefb39db9422.png)

and didn't matched with the sourcemap or for some other reason I haven't figured out completely the function
https://github.com/istanbuljs/v8-to-istanbul/blob/53c1cd89cb46f4cd2c0a23cdb31715de09716a2a/lib/source.js#L88-L92
returns null.

Hanving added some padding to the file I obtained the result expected which makes still think there's a bug in v8-to-instanbul
that needs to be fixed to avoid the issue... I keep on investigating and if possible I'll provide a PR

**Comment by glromeo** [comment]
I reopened the issue because a comparison of what happens with esbuild and rollup showed me that in both cases the sourcemaps produced don't have a mapping past the closing bracket and therefore both sourceMap.originalPositionFor return empty mapping. I am still unsure that originalEndPositionFor is to blame but at this point I would really like to hear your opinion on this

**Comment by glromeo** [comment]
What I understand is that neither of these calls:
https://github.com/istanbuljs/v8-to-istanbul/blob/53c1cd89cb46f4cd2c0a23cdb31715de09716a2a/lib/source.js#L201-L212
returns anything is the line is past the last one for which there is a mapping... looks like the bias works only within the line?
Unfortunately things get more obscure from here on:

https://github.com/mozilla/source-map/blob/58819f09018d56ef84dc41ba9c93f554e0645169/lib/source-map-consumer.js#L493-L504

**Comment by glromeo** [comment]
It turned out the issue was caused by the range in this filter:
https://github.com/istanbuljs/v8-to-istanbul/blob/53c1cd89cb46f4cd2c0a23cdb31715de09716a2a/lib/source.js#L78-L81

**Comment by bcoe** [comment]
@glromeo are we in a position to fix this now? It seems like the bad reports were actually inclusive vs., exclusive checks when incrementing line counts right?

**Comment by glromeo** [comment]
esbuild is emitting the mappings for ending `}` since 0.14.12... I consider this obsolete
