### ISSUE TITLE
Support `/* v8 ignore ...` hints

### ISSUE THREAD

**Issue by AriPerkkio** [istanbuljs/v8-to-istanbul#215]
This package is used by test runners which do not use [`c8`](https://github.com/bcoe/c8):
- https://jestjs.io/docs/configuration#collectcoverage-boolean
- https://vitest.dev/guide/coverage.html#ignoring-code

It's confusing for end users to have to ignore code using `/* c8 ignore next */` when these test runners have nothing to do with `c8`. 

I would suggest to add support for `/* v8 ignore ... */` syntax for ignore hints. The old `/* c8 ignore ... */` should be preserved for backwards compatibility. I'm happy to implement this.

**Comment by SimenB** [comment]
Yeah, I think that's a good idea! Happy to take a PR to that effect

**Comment by SimenB** [comment]
https://github.com/istanbuljs/v8-to-istanbul/releases/tag/v9.2.0
