### ISSUE TITLE
Question: batch support

### ISSUE THREAD

**Issue by ir-fuel** [istanbuljs/v8-to-istanbul#30]
Is it possible to use this somehow to convert the coverage of an entire project so we can visualise the coverage of running a test suite using istanbul (with their html output)?

**Comment by shinnn** [comment]
[c8](https://github.com/bcoe/c8) is just what you need.

**Comment by ir-fuel** [comment]
No idea what you mean? With c8 I can generate coverage files, but I would like to convert them for an entire codebase to HTML. This project seems to do it but only for one file.

**Comment by shinnn** [comment]
> With c8 I can generate coverage files, but I would like to convert them for an entire codebase to HTML.

I appreciate additional information but I'm still not fully understanding what you're trying to. I'll leave this issue to other maintainers.

**Comment by bcoe** [comment]
@ir-fuel sounds like you switched to Istanbul? I'm going to go ahead and close this.
