### ISSUE TITLE
Coverage formats very different when testing the same code via Jest and when converting from v8

### ISSUE THREAD

**Issue by dvail** [istanbuljs/v8-to-istanbul#56]
Hello, over the past week or so I have been doing a bit of experimenting with coverage reports generated from puppeteer-to-istanbul (and in turn this library) and comparing them to coverage reports generated from `jest --coverage`.

The final goal from all of this would be to generate coverage reports for unit/integration tests via Jest and coverage reports for e2e tests using Puppeteer and then merge them into one final coverage report that is then shipped off to SonarQube. The idea being that code missed by the unit tests might get covered by the e2e tests so I can get a more realistic view of total coverage.

The issue I'm having is that the branch/statement/function/line counts and coverage are completely different when running the same code in each test suite. I've got a minimal repo to demonstrate what I am seeing here https://github.com/dvail/istanbul-report-example and some screenshots of the html coverage reports that each test produces.

When running with Jest:
![image](https://user-images.githubusercontent.com/1292638/62669124-72765c00-b95c-11e9-904f-dc89bbaa66a2.png)

When running with Puppeteer:
![image](https://user-images.githubusercontent.com/1292638/62669148-8ae67680-b95c-11e9-9045-aa6819d3c3c7.png)

When running the Jest tests with c8 for good measure:
![image](https://user-images.githubusercontent.com/1292638/62669167-9f2a7380-b95c-11e9-9131-f5af4039049c.png)

In the first image, it seems like coverage is perfect. All hit and missed lines/branches/etc are detected and the counts at the top logically make sense.

In the second image, the coverage does seem _technically_ correct. Lines that are not hit are red, but everything else is considered covered. Even the comments and extraneous blank lines at the end of the file.

It seems to me that this is likely due to the differences in the way coverage is collected from the istanbul library and from v8 (described [here](https://medium.com/the-node-js-collection/rethinking-javascript-test-coverage-5726fb272949)), as the v8 coverage report looks almost identical to what is visible in Chrome when opening the sample page and viewing the coverage developer tab:
![image](https://user-images.githubusercontent.com/1292638/62669419-85d5f700-b95d-11e9-8513-3c0faaaf1883.png)

Is this something that is a known issue, or maybe just a limitation in the way coverage is reported from v8? Is there any reasonable way to combine coverage reports generated from the two tools, or is that something I should just not do? :)

Thanks!

(The code in question ties together istanbul, v8-to-istanbul, puppeteer-to-istanbul, nyc, and jest, but I figured that this would be the most appropriate project to post this in.)

**Comment by bcoe** [comment]
I believe the issue with Jest is most likely source-map related, there's an outstanding PR to add V8-based coverage to Jest:

https://github.com/facebook/jest/pull/8596

c8 does not currently have access to any source maps injected by Jest, so is likely unable to remap coverage appropriately.

Jest's built in coverage uses Istanbul, which is a completely different parser than V8, so I'm not shocked that there are discrepancies.

**Comment by dvail** [comment]
Ok thanks, that definitely makes sense. I'll track the jest issue and see if we can switch to all-v8 coverage sometime in the future.

**Comment by sijakret** [comment]
Did you manage to resolve this?
I am seeing the same issue with [web-test-runner](https://modern-web.dev/docs/test-runner/writing-tests/code-coverage/#writing-tests-code-coverage)

please excuse the cropped views but i think it get's the point across.

karma + babel + istanbul reporter
![image](https://user-images.githubusercontent.com/16835620/136632553-8e92b651-d827-4775-a833-6a48490f3d1a.png)
web test runner + chromium v8 + v8-to-istanbul
![image](https://user-images.githubusercontent.com/16835620/136632624-f65b4e1f-6f72-4661-943d-4d51fad6d39f.png)

any tips on how to ignore the irrelevant lines (i.e. imports, comments, etc..) ?
