### ISSUE TITLE
Library update

### ISSUE THREAD

**Issue by demurgos** [istanbuljs/v8-to-istanbul#6]
Hi,
I'm leaving a comment here to notify you that I am working on an update of the library. The main goal is to make it simpler and more reliable to improve `c8` (I originally started this to fix some `c8` bugs). I want this library to get production quality.

The changes are relatively large but form a coherent unit so I plan to send a single PR wen it's ready. I still take care to group logical changes into the same commit and provide helpful commit messages. You can track my current changes on my [next](https://github.com/demurgos/v8-to-istanbul/tree/next) branch.

Here are the main changes currently done:

## new API

[commit](https://github.com/demurgos/v8-to-istanbul/commit/79101f67a14233a79427a8a964760efc02730954)

The core job of `v8-to-istanbul` is to convert from one format to the other. This should be possible in one function.
Instead of asking the consumer to create a script, apply coverage and then query the Istanbul representation, this can be done in a single step: the user provides the script and coverage, the lib returns the Istanbul equivalent.
It is also the responsibility of the user to get the corresponding source text, the library does not read from disk. This removes the disk indirection and allows complete in-memory processing. The library should still provide helpers to convert V8 URLs to paths.
Finally there was a mismatch between the input and output values. It took a `FunctionCoverage[]` (coverage for a single file) but returned an Istanbul Report (coverage for many files). The new API returns the more fitting Istanbul equivalent: FileCoverage.
This makes the API pure and easier to test, reduces its scope and makes it easier to embed.

## Document library with Typescript

[Commit](https://github.com/demurgos/v8-to-istanbul/commit/9c3894fd972592e4afe65e1087ffac3c00380020) (and a few after it)

Getting familiar with the codebase was not easy. This library performs conversion from one format to the other, but it's hard to find documentation about these formats. Questions such as "what does the input look like?", "what is a location?", "what are valid `branch` values?", "should this be a hit count or array of hit counts?" caused me to lose a lot of time. Typescript is the established solution to solve these kinds of issues and helps a lot with documentation so I integrated it to the lib.
It also comes with a type checker and is a great quality of life improvement for consumers using VS Code or WebStorm/Intellij (their intellisense uses TS types, even for JS).

## Add fixture generation code

[Commit](https://github.com/demurgos/v8-to-istanbul/commit/bca6aa5d7cc97276d37c51bc8182fa0afda3f81f)

The library currently has two JS files and their corresponding V8 coverage results. It is not clear how these coverages where generated and how to reproduce them. It was probably done with c8 but I don't want to add it because it would create a cycle. `v8-to-istanbul` only needs a few sample files, it does not have to deal with subprocesses or CLI, so I added a small script to generate the fixtures here. It also enables you to easily add more tests and generate more V8 coverages.

---

That's all for the changes that are mostly done, but there a still a few things that need to be completed.

## Proper conversion, not line-based

The library currently uses a line based approach. It's a good first approximation, but it's not very clean. V8 returns precise ranges letting you handle parts of expressions or statements, statements spanning other multiple lines, etc. This lib should work on an AST level and report exact values for statements, branches and functions.
This would be another breaking change and that's why I want to wait to finish it before sending my PR.

## Exposes helpers

The public API should expose helpers to parse the V8 URL, handle the CJS wrapper, merge V8 coverages (they should probably be moved to their own repo at some point).

## Integration with other tools

Travis, Appveyor, Codecov, etc. See #4 and #5

---

These are the main changes. I hope to send my PR during this week but prefer to avoid setting any deadline.

**Comment by bcoe** [comment]
@demurgos thanks for this hard work, catch me here and let's chat about combining our goals for v8 test coverage in Node:

http://devtoolscommunity.herokuapp.com/

**Comment by demurgos** [comment]
I am closing this issue. Following my discussions with @bcoe, AST-based processing is out of scope for this lib.

I implemented a version using the AST in [istanbulize](https://github.com/demurgos/istanbulize).
